# SpotGEO 残差backbone单帧训练配置文件
# 使用方法: python scripts/train_singleframe.py --config configs/singleframe_res.yaml

# ================================
# 数据配置
# ================================
data:
  # train_dir: "../autodl-fs/SpotGEOv2/train"           # 训练数据目录路径
  # train_anno: "../autodl-fs/SpotGEOv2/train_anno.json"  # 训练标注文件路径
  # val_dir: "../autodl-fs/SpotGEOv2/test"               # 验证数据目录路径（使用test数据）
  # val_anno: "../autodl-fs/SpotGEOv2/test_anno.json"   # 验证标注文件路径
  train_dir: "datasets/SpotGEOv2/train"
  train_anno: "datasets/SpotGEOv2/train_anno.json"
  val_dir: "datasets/SpotGEOv2/test"
  val_anno: "datasets/SpotGEOv2/test_anno.json"
# ================================
# 数据增强配置
# ================================
# augmentation:
#   use_advanced: true  # 使用高级数据增强

# ================================
# 模型配置
# ================================
model:
  name: "spotgeo_res_fusion"              # 残差backbone模型名称
  config:                          # 模型特定配置
    # 残差网络配置
    backbone_type: "resnet"        # 骨干网络类型 (resnet/conv)
    res_block_type: "basic"        # 残差块类型 (basic/bottleneck)
    res_blocks_per_layer: [2, 2, 2, 2]  # 每层残差块数量
    
    # 网络结构配置
    backbone_channels: [64, 128, 256, 384]  # 骨干网络通道数
    detection_channels: [256, 128, 64]      # 检测头通道数
    num_classes: 1                  # 类别数量
    
    # FPN配置
    fpn_channels: 64               # FPN特征通道数（修改为缩放后的通道数）
    
    # 模型优化配置
    use_bn: true                   # 是否使用批归一化
    dropout: 0.1                   # Dropout比率
    scale_factor: 1             # 模型缩放因子（减少参数量）
    
    # 软标签配置
    soft_target:
      enabled: true                # 是否启用软标签
      alpha: 3.0                   # 高斯核大小（特征图像素单位）
      sigma: 0.8                   # 高斯分布的标准差
      min_value: 0.1               # 最小权重阈值（低于此值截断为0）
      dynamic_sigma:               # 动态调整sigma的配置
        enabled: false             # 是否启用动态调整
        init_sigma: 1.2            # 初始sigma值
        final_sigma: 0.8           # 最终sigma值
        schedule: "linear"         # 调整策略：linear/cosine/step

    # 损失函数配置
    loss:
      cls_weight: 1.0              # 分类损失权重
      reg_weight: 1.0              # 回归损失权重
      cls_config:                  # 分类损失配置
        loss_type: "focal"         # 损失类型：focal 或 binary
        alpha: 0.75                # Focal Loss 的 alpha 参数（平衡正负样本）
        gamma: 1.5                 # Focal Loss 的 gamma 参数（聚焦参数）
        reduction: "none"          # 损失归约方式
        pos_weight: 20.0            # 正样本权重
      reg_config:                  # 回归损失配置
        reduction: "none"          # 损失归约方式

# ================================
# 训练配置
# ================================
training:
  # 基本训练参数
  batch_size: 64                 # 批次大小（可根据GPU内存调整）
  num_workers: 4                   # 数据加载器工作进程数
  epochs: 800                     # 训练轮数
  lr: 0.0005                       # 学习率
  
  # 优化器和调度器
  optimizer: "adam"                # 优化器类型 (adam/sgd)
  scheduler: "cosine"                # 学习率调度器 (step/cosine/none)
  scheduler_config:                # 学习率调度器配置
      T_max: 150
      eta_min: 0.00001
  #  step_size: 50                  # 每隔多少个epoch降低学习率
  #  gamma: 0.5                     # 学习率衰减因子 
 
  # 训练控制
  checkpoint_interval: 10          # 检查点保存间隔（epoch）
  eval_interval: 5                 # 验证间隔（epoch）
  early_stopping_patience: 100     # 早停耐心值（残差网络可能需要更多时间收敛）

# ================================
# 输出配置
# ================================
output:
  output_dir: "outputs"            # 输出根目录
  experiment_name: "singleframe_res_p2_focal_soft"  # 实验名称

# ================================
# 设备配置
# ================================
device: "auto"                     # 训练设备 (auto/cuda/cpu)

# ================================
# 日志配置
# ================================
logging:
  use_swanlab: True                 # 是否使用swanlab记录
  swanlab_project: "spotgeo-singleframe-res"  # swanlab项目名称
  swanlab_mode: "cloud"             # swanlab模式: "cloud" (在线), "offline" (离线), "local" (本地)
  log_batch_metrics: True  # 是否记录每个batch的指标
  log_gradients: True      # 是否记录梯度信息

# ================================
# 后处理配置
# ================================
postprocessing:
  conf_thresh: 0.5                 # 置信度阈值
  topk: 30                       # 保留的top-k预测

# ================================
# 其他配置
# ================================
seed: 3407                          # 随机种子 