# SpotGEO 残差backbone快速测试配置文件
# 使用方法: python scripts/train_singleframe.py --config configs/singleframe_res_debug.yaml

# ================================
# 数据配置
# ================================
data:
  train_dir: "datasets/SpotGEOv2/train"           # 训练数据目录路径
  train_anno: "datasets/SpotGEOv2/train_anno.json"  # 训练标注文件路径
  val_dir: "datasets/SpotGEOv2/test"               # 验证数据目录路径（使用test数据）
  val_anno: "datasets/SpotGEOv2/test_anno.json"   # 验证标注文件路径

# ================================
# 模型配置
# ================================
model:
  name: "spotgeo_res"              # 残差backbone模型名称
  config:                          # 模型特定配置
    # 残差网络配置
    backbone_type: "resnet"        # 骨干网络类型 (resnet/conv)
    res_block_type: "basic"        # 残差块类型 (basic/bottleneck)
    res_blocks_per_layer: [1, 1, 1, 1]  # 每层残差块数量（减少用于快速测试）
    
    # 网络结构配置
    backbone_channels: [32, 64, 128, 256]  # 骨干网络通道数（减少用于快速测试）
    detection_channels: [128, 64, 32]      # 检测头通道数（减少用于快速测试）
    num_classes: 1                  # 类别数量
    
    # 模型优化配置
    use_bn: true                   # 是否使用批归一化
    dropout: 0.1                   # Dropout比率
    scale_factor: 0.5              # 模型缩放因子（进一步减少参数量）

# ================================
# 训练配置
# ================================
training:
  # 基本训练参数
  batch_size: 8                    # 批次大小（减小用于快速测试）
  num_workers: 2                   # 数据加载器工作进程数（减少用于快速测试）
  epochs: 5                        # 训练轮数（减少用于快速测试）
  lr: 0.001                        # 学习率（稍微增大用于快速收敛）
  
  # 优化器和调度器
  optimizer: "adam"                # 优化器类型 (adam/sgd)
  scheduler: "step"                # 学习率调度器 (step/cosine/none)
  
  # 训练控制
  checkpoint_interval: 2           # 检查点保存间隔（epoch）
  eval_interval: 1                 # 验证间隔（epoch）
  early_stopping_patience: 3      # 早停耐心值（减少用于快速测试）

# ================================
# 输出配置
# ================================
output:
  output_dir: "outputs"            # 输出根目录
  experiment_name: "singleframe_res_debug"  # 实验名称

# ================================
# 设备配置
# ================================
device: "auto"                     # 训练设备 (auto/cuda/cpu)

# ================================
# 日志配置
# ================================
logging:
  use_wandb: false                 # 是否使用wandb记录
  wandb_project: "spotgeo-singleframe-res-debug"  # wandb项目名称

# ================================
# 后处理配置
# ================================
postprocessing:
  conf_thresh: 0.5                 # 置信度阈值
  topk: 50                        # 保留的top-k预测（减少用于快速测试）

# ================================
# 其他配置
# ================================
seed: 42                          # 随机种子 