# SpotGEO 单帧训练配置文件
# 使用方法: python scripts/train_singleframe.py --config configs/singleframe_train.yaml

# ================================
# 数据配置
# ================================
data:
  train_dir: "datasets/SpotGEOv2/train"           # 训练数据目录路径
  train_anno: "datasets/SpotGEOv2/train_anno.json"  # 训练标注文件路径
  val_dir: "datasets/SpotGEOv2/test"               # 验证数据目录路径（使用test数据）
  val_anno: "datasets/SpotGEOv2/test_anno.json"   # 验证标注文件路径

# ================================
# 模型配置
# ================================
model:
  name: "spotgeo"                   # 模型名称
  config:                           # 模型特定配置
    backbone_channels: [64, 128, 256, 512]  # 骨干网络通道数
    detection_channels: [256, 128, 64]      # 检测头通道数
    num_classes: 1                  # 类别数量
    use_bn: true                   # 是否使用批归一化
    dropout: 0.1                   # Dropout比率

# ================================
# 训练配置
# ================================
training:
  # 基本训练参数
  batch_size: 16                   # 批次大小（可根据GPU内存调整）
  num_workers: 4                   # 数据加载器工作进程数
  epochs: 100                      # 训练轮数
  lr: 0.0001                        # 学习率
  
  # 优化器和调度器
  optimizer: "adam"                # 优化器类型 (adam/sgd)
  scheduler: "step"                # 学习率调度器 (step/cosine/none)
  
  # 训练控制
  checkpoint_interval: 10          # 检查点保存间隔（epoch）
  eval_interval: 1                 # 验证间隔（epoch）
  early_stopping_patience: 15     # 早停耐心值

# ================================
# 输出配置
# ================================
output:
  output_dir: "outputs"            # 输出根目录
  experiment_name: "singleframe_v1"  # 实验名称（可为null使用时间戳）

# ================================
# 设备配置
# ================================
device: "auto"                     # 训练设备 (auto/cuda/cpu)

# ================================
# 日志配置
# ================================
logging:
  use_swanlab: false                 # 是否使用swanlab记录
  swanlab_project: "spotgeo-singleframe"  # swanlab项目名称

# ================================
# 其他配置
# ================================
seed: 42                          # 随机种子 