# SpotGEO 残差backbone单帧训练配置文件 - 修复版本
# 解决F1值早期下降问题

# ================================
# 数据配置
# ================================
data:
  train_dir: "datasets/SpotGEOv2/train"
  train_anno: "datasets/SpotGEOv2/train_anno.json"
  val_dir: "datasets/SpotGEOv2/test"
  val_anno: "datasets/SpotGEOv2/test_anno.json"

# ================================
# 模型配置
# ================================
model:
  name: "spotgeo_res"
  config:
    backbone_type: "resnet"
    res_block_type: "basic"
    res_blocks_per_layer: [2, 2, 2, 2]
    backbone_channels: [64, 128, 256, 512]
    detection_channels: [256, 128, 64]
    num_classes: 1
    use_bn: true
    dropout: 0.1
    scale_factor: 0.25

# ================================
# 训练配置 - 修复版本
# ================================
training:
  batch_size: 16
  num_workers: 4
  epochs: 400
  lr: 0.0001
  
  # 优化器和调度器
  optimizer: "adam"
  scheduler: "step"  # 改用步进调度器
  
  # 训练控制
  checkpoint_interval: 10
  eval_interval: 2   # 更频繁验证
  early_stopping_patience: 30

# ================================
# 后处理配置 - 关键修复
# ================================
postprocessing:
  conf_thresh: 0.1   # 降低置信度阈值，适应训练早期
  topk: 50          # 减少输出数量

# ================================
# 输出配置
# ================================
output:
  output_dir: "outputs"
  experiment_name: "singleframe_res_fixed"

# ================================
# 设备配置
# ================================
device: "auto"

# ================================
# 日志配置
# ================================
logging:
  use_wandb: false
  wandb_project: "spotgeo-singleframe-fixed"

# ================================
# 其他配置
# ================================
seed: 42 